mutation AddPlayer ($name: String!, $position: String!, $dob: String!, $nationality: String!, $currentTeam: String!, $jerseyNumber: String!) {
  createOnePlayer (
    data: {
      name: $name,
      position: $position,
      dob: $dob,
      nationality: $nationality,
      currentTeam: $currentTeam,
      jerseyNumber: $jerseyNumber
    }
  ) {
      id
  }
}