mutation UpdatePlayer ($id: String!, $name: String!, $position: String, $dob: String, $nationality: String!, $currentTeam: String!, $jerseyNumber: String) {
  updateOnePlayer (where:
    { id: $id},
    data: { 
    name: $name,
    position: $position,
    dob: $dob,
    nationality: $nationality,
    currentTeam: $currentTeam,
    jerseyNumber: $jerseyNumber
    }
  ) {
      id
  }
}